# Generated by Django 4.1.2 on 2022-10-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=50)),
                ("client_lastname", models.CharField(max_length=50)),
                ("client_address", models.CharField(max_length=100)),
                ("client_telephone", models.CharField(max_length=15)),
                ("client_email", models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_name", models.CharField(max_length=50)),
                ("employee_lastname", models.CharField(max_length=50)),
                ("employee_address", models.CharField(max_length=100)),
                ("employee_telephone", models.CharField(max_length=15)),
                ("employee_birthday", models.DateField()),
                ("employee_username", models.CharField(max_length=80)),
                ("employee_password", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=12)),
                ("invoice_product_quantity", models.IntegerField()),
                ("invoice_subtotal", models.FloatField()),
                ("invoice_total", models.FloatField()),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ferretic.client",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ferretic.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.CharField(max_length=12)),
                ("order_product_quantity", models.IntegerField()),
                ("order_subtotal", models.FloatField()),
                ("order_total", models.FloatField()),
                (
                    "employee_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ferretic.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=50)),
                ("product_description", models.TextField(max_length=80)),
                ("product_price", models.FloatField()),
                ("product_stock", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor_name", models.CharField(max_length=80)),
                ("vendor_address", models.CharField(max_length=100)),
                ("vendor_telephone", models.CharField(max_length=15)),
                ("vendor_email", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Order_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                (
                    "order_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="ferretic.order"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ferretic.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="vendor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="ferretic.vendor"
            ),
        ),
        migrations.CreateModel(
            name="Invoice_product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ferretic.invoice",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="ferretic.product",
                    ),
                ),
            ],
        ),
    ]
