# Generated by Django 4.1.2 on 2022-10-30 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice", name="invoice_subtotal", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="invoice", name="invoice_total", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order", name="order_subtotal", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="order", name="order_total", field=models.IntegerField(),
        ),
    ]
