# Generated by Django 4.1.2 on 2022-10-30 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0002_alter_invoice_invoice_subtotal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_email",
            field=models.EmailField(max_length=254),
        ),
    ]
