# Generated by Django 4.1.2 on 2022-10-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0003_alter_client_client_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="vendor_email",
            field=models.EmailField(max_length=254),
        ),
    ]
