# Generated by Django 4.1.2 on 2022-10-31 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0004_alter_vendor_vendor_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice", old_name="client_id", new_name="client",
        ),
        migrations.RenameField(
            model_name="invoice", old_name="employee_id", new_name="employee",
        ),
        migrations.RenameField(
            model_name="invoice_product", old_name="invoice_id", new_name="invoice",
        ),
        migrations.RenameField(
            model_name="invoice_product", old_name="product_id", new_name="product",
        ),
        migrations.RenameField(
            model_name="order", old_name="employee_id", new_name="employee",
        ),
        migrations.RenameField(
            model_name="order", old_name="vendor_id", new_name="vendor",
        ),
        migrations.RenameField(
            model_name="order_product", old_name="order_id", new_name="order",
        ),
        migrations.RenameField(
            model_name="order_product", old_name="product_id", new_name="product",
        ),
    ]
