# Generated by Django 4.1.2 on 2022-10-31 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0005_rename_client_id_invoice_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="invoice", name="invoice_product_quantity",),
        migrations.RemoveField(model_name="invoice", name="invoice_subtotal",),
        migrations.RemoveField(model_name="invoice", name="invoice_total",),
        migrations.RemoveField(model_name="order", name="order_product_quantity",),
        migrations.RemoveField(model_name="order", name="order_subtotal",),
        migrations.RemoveField(model_name="order", name="order_total",),
        migrations.AddField(
            model_name="invoice_product",
            name="invoice_product_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice_product",
            name="invoice_subtotal",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invoice_product",
            name="invoice_total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order_product",
            name="order_product_quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order_product",
            name="order_subtotal",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order_product",
            name="order_total",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
