# Generated by Django 4.1.2 on 2022-11-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0007_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_birthday",
            field=models.CharField(max_length=15),
        ),
    ]
