# Generated by Django 4.1.2 on 2022-11-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ferretic", "0008_alter_employee_employee_birthday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="employee_birthday",
            field=models.CharField(max_length=15),
        ),
    ]
