# Generated by Django 4.1.3 on 2022-11-12 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0009_alter_user_employee_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='employee_address',
            new_name='User_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_birthday',
            new_name='User_birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_lastname',
            new_name='User_lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_name',
            new_name='User_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_password',
            new_name='User_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_telephone',
            new_name='User_telephone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='employee_username',
            new_name='User_username',
        ),
    ]
