# Generated by Django 4.1.3 on 2022-11-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0010_rename_employee_address_user_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='User_address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_birthday',
            new_name='user_birthday',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_lastname',
            new_name='user_lastname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_name',
            new_name='user_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_password',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_telephone',
            new_name='user_telephone',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_username',
            new_name='user_username',
        ),
    ]
