# Generated by Django 4.1.3 on 2022-11-18 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0010_purchase_sold_remove_order_product_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
