# Generated by Django 4.1.3 on 2022-11-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0011_rename_employee_id_order_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='employee_id',
            new_name='employee',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='invoice_id',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='sold',
            old_name='product_id',
            new_name='product',
        ),
    ]
