# Generated by Django 4.1.3 on 2022-11-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0012_rename_client_id_invoice_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sold',
            name='sold_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
