# Generated by Django 4.1.3 on 2022-11-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferretic', '0013_client_client_enabled_employee_employee_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
